### ISSUE TITLE
Propose collations onto SMC

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#106]
In particular, this involves implementing the proposer here: https://github.com/prysmaticlabs/geth-sharding/blob/master/sharding/proposer/proposer_client.go

Blocked by #89

**Comment by terenc3t** [comment]
I'll take on this. Will open a PR after #97

**Comment by terenc3t** [comment]
To add more color into this issue. Here are the major functions a proposer will implement:

- Creates collation
- Signs collation
- Sends `addHeader` transaction to SMC
- Broadcasts the CollationBody to shard network

**Comment by rauljordan** [comment]
This was closed by #111
