### ISSUE TITLE
Notaries vote on collations

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#107]
This would involve cleaning up the notary logic here: https://github.com/prysmaticlabs/geth-sharding/blob/master/sharding/notary/notary.go

As well as implementing the necessary actions for a notary to take each period.

Blocked by #89

**Comment by nisdas** [comment]
I will be taking this on after I am done with #92

**Comment by rauljordan** [comment]
Closing due to #230.
