### ISSUE TITLE
Clients store chaindata in local KV store and can produce it later

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#109]
Extending #99... this is a tracking issue for clients to store their chain data such that they can produce it when they receive the message "Hey, do you have collation 55?" and they can respond with collation 55.

**Comment by rauljordan** [comment]
Perfect, I will take charge on this after #100. This will most likely involve having an event that is triggered through p2p and will fetch the collation information stored in the local file system.
