### ISSUE TITLE
Setup a Simple libp2p Echo Server as a Service Attached to Sharding Node

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#129]
Hi all,

As a simple way to integrate libp2p and to begin our experimentation of libp2p into our repo, we can start by setting up a bootnode that serves a simple echo server, and attach another libp2p node to our sharding node as a `Service` (see #127). Let's keep this constrained a package called `p2p` under the `sharding` package in our repo.

We can register this echo service in the `registerShardingServices` func in `cmd/geth/shardingcmd.go`

```go
// registerShardingServices sets up either a notary or proposer
// sharding service dependent on the ClientType cli flag. We should be defining
// the services we want to register here, as this is the geth command entry point
// for sharding.
func registerShardingServices(n node.Node) error {
	protocolFlag := n.Context().GlobalString(utils.ProtocolFlag.Name)

	err := n.Register(func(ctx *cli.Context) (sharding.Service, error) {
		// TODO(terenc3t): handle case when we just want to start an observer node.
		if protocolFlag == "notary" {
			return notary.NewNotary(n.Context(), n)
		}
		return proposer.NewProposer(n.Context(), n)
	})

	if err != nil {
		return fmt.Errorf("failed to register the main sharding services: %v", err)
	}

	// TODO: registers the shardp2p service.
	// we can do n.Register and initialize a shardp2p.NewServer() or something like that.
	return nil
}
```

Then, in the submit collation function of the `notary` package, as the notary protocol will have access to the sharding node, we can call out an echo request using this shardp2p service and get an output.

## What This Achieves

This would at least allow us to get our hands dirty with libp2p and see how we can write useful functions we can call throughout our notary or proposer protocols. This code will eventually evolve into registering another service in the sharding node for discovery, and more.

**Comment by rauljordan** [comment]
Could be interesting to check out the work done in other PR's like: https://github.com/ethereum/go-ethereum/pull/16419

**Comment by terenc3t** [comment]
I'm also interested in the development of this [thread](https://github.com/libp2p/libp2p/issues/33)

**Comment by rauljordan** [comment]
#149 simplifies this immensely, as this can be constrained to the `p2p` subpackage in the `sharding` package and attached as a service to `ShardEthereum`
