### ISSUE TITLE
Optimize collation serializer and deserializer functions

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#134]
We can further optimize collation serializer and deserializer collations functions as the following: 
- Serializer function should be pure, it should not depend on a collation pointer receiver
- `collation.Serialize()` can be deleted because we can get the same data from `collation.Body()`
- `collation.Deserialize()` can be deleted because we can get the same data from `collation.Transactions()`

I can take on this issue because it's currently blocking #111

**Comment by prestonvanloon** [comment]
Is this done with #136?

**Comment by terenc3t** [comment]
Yup. We can close
