### ISSUE TITLE
Shard Node and ShardProtocolManager Design

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#148]
Hi all,

Moving forward on #143, let's come up with a design for a `ShardEthereum` and `ShardProtocolManager` in line with Geth's way of doing things.

For context, refer to #143.

## Entry Point

When we call `geth sharding`, we configure a geth node using the `makeFullNode` defined in `cmd/geth/config.go`, where a function called `utils.RegisterEthService` is currently called. This function determines whether to start a full Ethereum node or a light Ethereum node. 

```go
// RegisterEthService adds an Ethereum client to the stack.
func RegisterEthService(stack *node.Node, cfg *eth.Config) {
	var err error
	if cfg.SyncMode == downloader.LightSync {
		err = stack.Register(func(ctx *node.ServiceContext) (node.Service, error) {
			return les.New(ctx, cfg)
		})
	} else {
		err = stack.Register(func(ctx *node.ServiceContext) (node.Service, error) {
			fullNode, err := eth.New(ctx, cfg)
			if fullNode != nil && cfg.LightServ > 0 {
				ls, _ := les.NewLesServer(fullNode, cfg)
				fullNode.AddLesServer(ls)
			}
			return fullNode, err
		})
	}
	if err != nil {
		Fatalf("Failed to register the Ethereum service: %v", err)
	}
}
```

Here, we can check the config options to register either a light eth node, full node, or **shard node**. If **shard node** is in the config, we do:

```
err = stack.Register(func(ctx *node.ServiceContext) (node.Service, error) {
    return sharding.New(ctx, cfg)
})
```

The `sharding.New` func accomplishes the same as what the `les` or `eth` package's `.New` functions do, which is to setup a protocol manager and start all the responsibilities of a light/full node.

## Shard Node

Following the convention of the `les` and `eth` packages, we define the `.New` function in `sharding/backend.go` as follows:

```go
func New(ctx *node.ServiceContext, config *eth.Config) (*ShardEthereum, error) {
	chainDb, err := eth.CreateDB(ctx, config, "shardchaindata")
	if err != nil {
		return nil, err
	}
	chainConfig, genesisHash, genesisErr := core.SetupGenesisCollation(...)
	if _, isCompat := genesisErr.(*params.ConfigCompatError); genesisErr != nil && !isCompat {
		return nil, genesisErr
	}
	log.Info("Initialised chain configuration", "config", chainConfig)

	peers := newPeerSet()
	quitSync := make(chan struct{})

	seth := &ShardEthereum{
		... // need to design this.
	}

	seth.relay = NewLesTxRelay(...)
	seth.serverPool = newServerPool(...)
	seth.retriever = newRetrieveManager(...)
	seth.odr = NewLesOdr(...)
	if leth.blockchain, err = NewShard(...); err != nil {
		return nil, err
	}

	seth.txPool = NewTxPool(...)
	if seth.protocolManager, err = NewShardProtocolManager(...); err != nil {
		return nil, err
	}

	return seth, nil
}
```

Then, the `.Start()` func of this node would be similar to what `les` or `eth` does as well:

```go
// Start implements node.Service, starting all internal goroutines needed by the
// Ethereum protocol implementation.
func (s *ShardEthereum) Start(srvr *p2p.Server) error {
	s.serverPool.start(...)
	s.protocolManager.Start(...)
	return nil
}
```

## Shard Protocol Manager

The shard protocol manager should be responsible to give us shared access methods to the shardChainDb, underlying p2p primitives, and handling of messages between actors in a sharded system.

```go
type ShardProtocolManager struct {
    ... // need to design this.
}
```

The `NewShardProtocolManager` function should attach these important shared services, but the p2p aspect of it might very well be different as we are exploring go-floodsub/gossip-sub, so I will not elaborate on that. 

Now that this is in place, let's talk about the specific fields we'll have in `ShardEthereum` and `ShardProtocolManager`. Once we define these specifically, I can kick off a PR that implements these entry points and we can split up the rest among a bunch of PRs. @prestonvanloon @terenc3t @nisdas.

**Comment by prestonvanloon** [comment]
I propose we split up this design work into the following components:


- Shard server i.e. what's needed to start & bootstrap a sharded server while conforming to the geth node entrypoint.
- Shard protocol manager and how the actors can utlize this to enable their behavior.  
- More something else?

**Comment by rauljordan** [comment]
Closing for now as this will be explained by the design doc.

**Comment by prestonvanloon** [comment]
Discussion continued in the design doc draft: https://docs.google.com/document/d/1J4AEHTSKDGJpNzWS7ZXPqD0yEjqecb-xjdVkjGrxRMk/edit
