### ISSUE TITLE
Exploring SMC With New Registration and Dynamic Shard Count Properties

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#151]
## Background

This issue was created with inspirations from research threads: [Registrations, shard count and shuffling](https://ethresear.ch/t/registrations-shard-count-and-shuffling/2129/7) and [A proposal for structuring committees, cross-links](https://ethresear.ch/t/a-proposal-for-structuring-committees-cross-links-etc/2118).

Current SMC implementation was designed with minimal functionality to get us through [Ruby](https://ethresear.ch/t/minimal-sharding-protocol-extension/1823) release. It doesn't have support for RANDAO, cross links, dynamic shard count, proposer deposit, better shuffling mechanisms, the new elements mentioned in the latest research. Since those are all the critical components to make Sharding to work, it's important for us to iterate quick and keep our implementations up to date so we can provide our valuable inputs to the research threads.

## Ideas

I propose we get a head start on SMC 2.0. Keep in mind we'll still be using current SMC 1.0 for Ruby release. SMC2.0 is isolated from Ruby release, it will be prototyped and tested, but doesn't affect current Ruby release schedule. This makes a good `new-comer` and `bounty` issue

**Current SMC1.0 has the following features:**
- notary can register with a deposit, deregister with lock up period, and get deposit back when lock up ends
- anyone can add a header with shard ID, period and chunk root to the SMC
- notary gets shuffled per period and shard
- elected notary can submit its vote to the SMC

**We should add the following features to SMC 2.0:**
- notary and proposer are the same entity (i.e. same participant, same address)
- there are 3 states for register/deregister: `pendingRegister`, `registered`, `pendingDeregistered`
- `pendingRegister` and `pendingDeregister` are both fifo queues 
- smc tracks the current shard count
- if `pendingRegister` count reaches threshold (i.e. enough participant registered), smc increases `shardCount`
- if `pendingRegister` == `registered`, smc increases `shardCount`
- proposers and notaries are shuffled across shards. Proposers assigned to shards 2^19 periods. Notary 2^7 periods. Oldest proposer is shuffled 2^19-10 period. Oldest notary is shuffled 2^10-7 period
- active registered validator can deregister and count down begins. If `pendingRegister` > 0 and countDown period ends. The validator is immediately deregistered and replace by the top pendingRegister waiting in the queue

**Comment by rauljordan** [comment]
Very neat @terenc3t ! Agree with getting a head start. I actually would recommend attaching a bounty to this issue, as this is something best suited for outside contributors that want to learn more about sharding and contribute something immensely helpful.

Thoughts @prestonvanloon @nisdas ?

**Comment by rauljordan** [comment]
Tagging this as an intermediate issue.

**Comment by terenc3t** [comment]
Going to close this for now. Latest research has indicated we'll be moving away from SMC to beacon chain. This won't be relevant after Ruby release.
