### ISSUE TITLE
Handle the Functions in notary/service.go Through Goroutines

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#152]
As part of the refactor done in #149, we should use goroutines to make the entire flow of a notary's service concurrent. Right now, the following functions are blocking the rest of the services running in the ShardEthereum node:

```go
// Start the main routine for a notary.
func (n *Notary) Start() error {
	log.Info("Starting notary service")

	// TODO: handle this better through goroutines. Right now, these methods
	// are blocking.
	if n.smcClient.DepositFlag() {
		if err := joinNotaryPool(n.smcClient); err != nil {
			return err
		}
	}

	return subscribeBlockHeaders(n.smcClient)
}
```

Namely, joinNotaryPool and subscribeBlockHeaders.

**Comment by prestonvanloon** [comment]
@rauljordan I think you did this recently?
