### ISSUE TITLE
Define the Requirements and Functionality for an Observer Service

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#155]
In the minimal sharding protocol, we have 2 different types of actors: notaries and proposers. 

- Notaries are in charge of the voting/consensus layer of deciding on canonical collations and are also responsible for data availability checking. 
- Proposers are in charge of listening for incoming transactions over p2p, packaging them into collation bodies and broadcasting their respective headers to the Sharding Manager Contract

We posit that in our implementation, users would benefit from a third actor that we call an **observer**. If a user starts a sharding client without specifying a notary or proposer service, geth will simply start an **observer** service that hooks into the shardp2p network and is able to listen for events occurring throughout the network. This will be useful for nice logging and visualizations of what is occurring in the sharded system.

We have created an `observer` subpackage in our `sharding` package but have not yet defined exactly what it should do for our Ruby release. Starting this issue for anyone interested to take hold of a potential design.

Team, help me do a better job at scoping this issue into more tangible action items.

**Comment by terenc3t** [comment]
From discussing with the team last night, the role of the **observer** is really just a **client** sending TXs to **proposer**.  As discussed for Ruby release, we'll use **stimulator** to facilitate workflows between **proposer** and **notary**. Is there more work to do here?

**Comment by rauljordan** [comment]
Simulator is the one that will be generating transactions and broadcasting it to the p2p network. I don't see what observers should do in this system. They just connect to p2p for now, and that's it,

**Comment by prestonvanloon** [comment]
In the end, the **observer** is the same as what we consider a normal node on the Ethereum network. 

- Connect to the sharded universe
- Sync chains
- Provide interface for users to interact with Ethereum. This could be via console or exposing RPC endpoints. 

Essentially, it has the same capabilities as a proposer or notary, but has no role. 
This is the default state and there really is not much to design or define, in my opinion.

**Comment by nisdas** [comment]
Should we close this issue then since there really is not anything more to do ?

**Comment by prestonvanloon** [comment]
Yes. Closing since there isn't anything actionable here.
