### ISSUE TITLE
Integrate ShardDB Into the ShardEthereum Instance

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#156]
Now that we have defined `ShardEthereum` in `sharding/node/backend.go` to the main container for every single sharding service, we have decided it will contain properties important for shared access across these services. One of them is a `shardChainDb` property that will provide access to a persistent db (either leveldb, badger, or others). However, we have yet to initialize this shardChainDb.

Using the `sharding/database` subpackage, a PR for this issue would integrate the work that has already been done in the subpackage and work on adding support for levelDB or other key-value stores. It would attach an instance of this database to the `ShardEthereum` instance as `shardChainDb`, and verify that it can be used across different services.

**Comment by terenc3t** [comment]
Closed via #167
