### ISSUE TITLE
Allow user to specify whether he/she wants to become a validator upon client start

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#16]
Currently, the client will **automatically deposit 100ETH from the user's account** into the the VMC validator set. In the future, we need to allow users to specify whether or not they want to take this action, perhaps as a cli flag upon launching the sharding client.

`geth shard --joinvalidatorset`

will deposit the 100ETH automatically into the VMC.

`geth shard`

will start the client and **not** deposit the ETH automatically.

**Comment by terenc3t** [comment]
This is done via #41
