### ISSUE TITLE
Implement Notary Withdraw CLI

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#162]
Currently notary has no way to deregister and receive fund back using command line. I'd like to see this working for our Ruby release and to demo. 

The workflow for Notary:
1. notary register to notary pool with deposit
2. notary gets elected, vote on some collation headers
3. notary deregister, wait lockup period to end
4. notary fall back to observer role
5. lock up period ends, notary receives funds

For this PR, we care steps 3 - 5, and can split up the tasks as following:
- Implement new cli flag for notary to deregister/withdraw
- When shardNode gets cli flag, Notary service's `Stop()` function gets called
- Start Observer service

**Comment by rauljordan** [comment]
It seems like this has not even been decided for the beacon chain idea. If we are going to eventually move into beacon chain after ruby, I feel like it would be a waste of time to implement this. Should we close?

**Comment by terenc3t** [comment]
I agree. SMC is going to depreciate in favor of beacon chain. Client withdraw will use beacon chain logic instead of SMC logic. Will close this for now and open when beacon chain spec and implementation get more finalized
