### ISSUE TITLE
Transaction simulator tool

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#17]
Hey guys,

We'll need a transaction simulator tool that can start when the sharding client is launched so that the client can have stuff to process into collations on the shards. Ideally, we can turn this into an independent cli tool that we can launch while our geth node is running.

**Comment by prestonvanloon** [comment]
[Google doc](https://docs.google.com/document/d/1YohsW4R9dIRo0u5RqfNOYjCkYKVCmzjgoBDBYDdu5m0/edit?usp=sharing) on how this should work.
