### ISSUE TITLE
Breakdown Large Interfaces Into Smaller, More Useful Ones

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#183]
Hi all,

Part of effective go is the usage of interfaces as a way to enable easy refactoring and reusability of code through layers of abstraction. Interfaces are ideal when mocking certain methods in order to unit test small/medium size functions, yet we often end up having very large interfaces that map almost 1-to-1 to their implementation. That is, we define items such as:

```go
type Client interface {
    Account() *accounts.Account
    CreateTXOpts(value *big.Int) (*bind.TransactOpts, error)
    SMCCaller() *contracts.SMCCaller
    SMCTransactor() *contracts.SMCTransactor
    SMCFilterer() *contracts.SMCFilterer
    TransactionReceipt(common.Hash) (*types.Receipt, error)
    ChainReader() ethereum.ChainReader
    DepositFlag() bool
    SetDepositFlag(deposit bool)
    DataDirPath() string
    Sign(hash common.Hash) ([]byte, error)
    GetShardCount() (int64, error)
}
```
_in sharding/mainchain/smc_client.go_

Which we then use in functions such as:
```go
func isAccountInNotaryPool(client mainchain.Client) (bool, error) {
	account := client.Account()
	// Checks if our deposit has gone through according to the SMC.
	nreg, err := client.SMCCaller().NotaryRegistry(&bind.CallOpts{}, account.Address)
	if !nreg.Deposited && err != nil {
		log.Warn(fmt.Sprintf("Account %s not in notary pool.", account.Address.String()))
	}
	return nreg.Deposited, err
}
```
_in sharding/notary/notary.go_

Notice how we have an entire `Client` interface, yet this function (among others), only use the `SMCClient()` property and the `Account()` property. When testing this method, we have to mock an entire struct and include every single method in the `Client` interface when we could instead be more effective.

Instead, we could define a 
```go
type ContractCaller interface {
    SMCCaller()
}
```

as well as a 
```go
type AccountFetcher interface {
    Account()
}
```

and refactor this function to take in these interfaces. Testing in this case becomes incredibly easy, and the `*mainchain.SMCClient` struct ends up being an implementation of a composition of these smaller interfaces. I already started refactoring some aspects of this in my PR #172 as it was nearly impossible to test certain goroutines without having to mock every single method across a variety of interfaces.

Let's keep this in mind moving forward.

**Comment by terenc3t** [comment]
Thanks for opening this up. This will inherently solve #163 and #164
