### ISSUE TITLE
Notary: Request Collation Proposals Via P2P When Selected on a Shard

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#199]
Hi all,

Currently, we simulate requests from a `simulator` service that runs when a node runs as a Proposer. This service simulates incoming notary requests for collation bodies where the current node has to fetch the relevant information from persistent storage and respond accordingly. This is because we do not have the ability to communicate remotely across nodes until the first version of shardp2p is rolled out, which will be ready soon.

**Instead**, we will generate requests for collation bodies from within the `notary` package as part of a notary's workflow when being selected on a shard. The **notary** should issue requests for collation bodies during this time **instead** of the simulator package doing so.

**Comment by prestonvanloon** [comment]
@rauljordan can you outline the requirements for this? I don't understand the issue. 

Why do we need to simulate notary requests? Isn't the task to implement the request when the notary is selected?

**Comment by rauljordan** [comment]
@prestonvanloon that's what I meant, I'll update the description to make it clear. We are currently using simulator, but we do **not** want to use simulator but instead have this be part of the core logic of a notary's workflow.

**Comment by rauljordan** [comment]
Closing due to #230.
