### ISSUE TITLE
Notary: Implement Windback Sync, Fetch 25 Previous Canonical Collations From Other Nodes

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#200]
Hi all,

As part of the Ruby Release Product Requirements [doc](https://docs.google.com/document/d/125ajrN-0cKGwAMlv_bi02MKzGUxMDC_TeDvHCpqAKAs/edit#), we have defined one of the requirements of a Notary actor is to fetch the 25 canonical collation headers from the SMC previous to its currently assigned period number. This process is known as windback and it is an important component at the data availability layer for sharding.

### Requirements

PRs for this would implement the components of the **Windback Design Doc** written [here](https://docs.google.com/document/d/1l4HupeJdzMF0OrEO84srjkm-TWnyR6FNADjU1oYWlr8/edit#).

We can break down this feature into the following steps that can be tackled by PRs:

- A notary service running on a shard node is selected to notarize collations on a certain shard in a certain period (let’s say shard 1, period 40).
- The sharding node has to query the Sharding Manager Contract to determine the collation headers submitted by proposers on shard 1 from period 14 to 39 and store their header hashes in memory.
- The sharding node has to quickly discover notary peers on shard 1 and broadcast requests for the bodies corresponding to those header hashes on that shard.
- After the notary receives the data, it has to calculate a windback proof of custody for a concatenation of all 25 collation bodies received during the time frame.
- During the voting process, the notary has to broadcast its proofs of custody to the  sharding manager contract.
- The notary then persists this collation data received in its persistent data store until the end of the challenge period of its proof of custody.
- The notary can now handle incoming requests for collation bodies from other notaries during now that it has the data.

**Comment by prestonvanloon** [comment]
@rauljordan Is there any sync design you could share?

**Comment by rauljordan** [comment]
Hey @prestonvanloon, I added a reference to the sync design doc. I don't think a simple version of this would require extensive design, as we can simply fetch the headers from the collation records in the SMC and then broadcast requests for them from within the notary package. I believe this can be done through a well-scoped, fleshed out PR.

**Comment by rauljordan** [comment]
Closing due to #230.
