### ISSUE TITLE
Notary: Configure the Persisting of Collation Data in Local Storage

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#201]
Hi all,

(TL;DR: A PR for this should configure a flag that allows a user to specify how long it wants to persist data and a sharding client should know when to delete the data when the specified time is reached)

As part of the minimal sharding protocol, notaries are in charge with checking for data availability of collation bodies submitted to the Sharding Manager Contract. Once a notary is selected on a shard at a certain period, the notary has to:

- Fetch the collation headers submitted to the contract during that assigned period
- Broadcast requests to fetch their corresponding bodies from the shardp2p network
- Mark collations as available or unavailable
- Submit a vote on a valid, available collation at the end of the period
- Get reshuffled into a different shard on a different period

The problem with this approach is there is **no incentive** for notaries to persist this data in their local storage, making them prone to the **validator's dilemma** where they can be lazy and just say that a collation was available when it was not. To solve this problem, the research introduces the concept of a proof of custody, which means that when submitting a vote, a notary has to combine his/her signature with chunks of the merklization of the collation body in question into a single Merkle root. This combination allows others to have confidence the notary **has the collation data** at the time of voting, as this is the only way this value could be computed.

Other nodes can then **challenge** these notaries during a certain time frame known as a **challenge period** that corresponds to the proof of custody. Notaries are incentivized to hold onto their downloaded collation data at least until the length of the challenge period is over. This challenge period is a public parameter that was added to the Sharding Manager Contract in #168.

### Challenge, Response Mechanism

If a notary is challenged before the time period is up, the notary has a maximum **response window** in which it can respond to the request before being punished. 

We will **NOT** implement the challenge response mechanism as part of the Ruby release, but we will implement a PR in our code that persists collation data in a notary node and periodically checks when the challenge period is over.

Then, using a CLI flag for configuration, the node knows the maximum time period it can hold the data before it deletes it. This amount of time is **at least challenge_period + response_period** long. 

Purging is done by deleting all downloaded collation body information from the persistent key-value store in a notary node once the challenge period is over (if the notary received no challenges) or challenge period + response period (if the notary received a challenge).

A PR for this should configure this purge timeframe and allow the user to specify how long it wants to persist data, and should automatically delete the data from storage once the timeframe is over.

### References

- [Extending Skin in the Game Of Notarization With Proofs of Custody](https://ethresear.ch/t/extending-skin-in-the-game-of-notarization-with-proofs-of-custody/1639)
- [Minimal Sharding Protocol](https://ethresear.ch/t/a-minimal-sharding-protocol-that-may-be-worthwhile-as-a-development-target-now/1650)

**Comment by prestonvanloon** [comment]
Please add more context to the requirements. We need to provide more information for a outside contributor to pick this up. 

- How long is the challenge period? How will the notary know if the challenge period has ended?
- What about if they are challenged just before the period ends? Shouldn't we have some buffer and a check to be sure we aren't being challenged before purging this data?
- What flag will you use to determine whether or not to purge? (Think about archival nodes)
- How is purging done?

**Comment by rauljordan** [comment]
Hey @prestonvanloon updated the issue description to answer all your questions.

**Comment by rauljordan** [comment]
Closing due to #230.
