### ISSUE TITLE
Add MockNode Into Internals Package

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#202]
We currently use the `type mockNode{} struct` across a variety of tests and we could easily abstract this repeated code into the `sharding/internal` package that can be imported in the tests requiring it.

The refactoring of tests using this struct should be done through separate PRs

**Comment by prestonvanloon** [comment]
The mockclient was copied to internal package and the test code still needs to be refactored/cleaned up to use this internal package helper.

**Comment by rauljordan** [comment]
Updated the issue description to clarify @prestonvanloon
