### ISSUE TITLE
Write Unit Tests and Reach Solid Coverage on the Mainchain Package

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#203]
Hi all,

With our goal of reaching high code coverage on our services in the sharding client, we want to ensure the mainchain package is well-tested as it contains critical code for our functionality. A PR for this should attempt to reach this goal in an effective manner through good use of smaller interfaces.

**Comment by prestonvanloon** [comment]
To shine a bit of light on this issue: we are hoping to reach complete code coverage and testing on the sharding/mainchain package. This would involve some refactoring, better uses of smaller interfaces, and best practices with regards to testing.

The only specific requirements to close this are that the coverage is at 100%. 
Please consider breaking up work into small pull requests for easier review.

**Comment by rauljordan** [comment]
Closing due to #230.
