### ISSUE TITLE
Notary: Receive Collation Bodies via P2P and Vote on Data Availability

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#205]
Currently, a Notary is able to create requests for collation bodies and broadcast them to the shardp2p network. Other nodes respond to those requests but notaries do nothing with the received responses. A PR for this should take the collation body responses, keep track of their data availability by persisting them in local storage, and vote on one collation using the proof of custody method into the  SMC.

**Comment by prestonvanloon** [comment]
Is there any design to add here? @terenc3t

**Comment by rauljordan** [comment]
Closing due to #230.
