### ISSUE TITLE
Every Node Should Handle Collation Data Requests, Not Just Proposers

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#206]
As part of the Ruby Release PR Doc, every node in the network should be able to handle incoming requests for collation data. Right now, only proposers are able to respond. With the merging of #196, we can extend this functionality to every node.

Assigning provisionally to @terenc3t and he is the creator of #196.

**Comment by prestonvanloon** [comment]
Why are proposers the only ones able to do this? Isn't the sync/data service independent of the actor role?

**Comment by terenc3t** [comment]
Currently proposers are the only ones able to handle incoming requests for collation data (Why? because we are not storing signature in SMC) 
We need to extend this functionality to the rest of the actors.
