### ISSUE TITLE
Sharding Node Service Context is Returning Copies of Dependencies

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#215]
https://sourcegraph.com/github.com/prysmaticlabs/geth-sharding/-/blob/sharding/interfaces.go?utm_source=share#L56:12

The `RetrieveService` method is doing the following:
- Creating a new value of type `v`.
- Assigning the value of the service of type v to this new value on the interface param provided.

In short, this is making a copy of the value.

This service method must 
- Return a pointer
- Consistently return the same pointer over multiple method calls

See this pseudo-code below:
```golang
ptr1 := ...
ptr2 := ...
ptr3 := ...

ptr1 == ptr2 == ptr3
```

Over 3 method calls, all three pointers should be the same address.

**Comment by rauljordan** [comment]
Closed by #217
