### ISSUE TITLE
Port Over the Beacon Chain Repo as a Bazel Subpackage in Geth-Sharding

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#244]
Hi all,

Based on the decisions taken in the [random beacon chain design doc](https://docs.google.com/document/d/1lTDUy6JwRGNE4rDKiyzaV-lxhG2SZ2F6wCthM-QCSFQ/edit#), we can start porting over the [beacon chain repo](https://github.com/prysmaticlabs/beacon-chain) into geth-sharding as we intend to create a monorepo.

A PR for this will most likely have to use bazel target rules to set visibility as subpackages for both sharding and beacon chain within this repo.

We can split the work up for this across a few PRs, namely, one will probably also create a third and fourth project in the repo called `contracts` and `shared`, where all our smart contracts and common packages can be contained and given a public visibility bazel target rule.

**Comment by terenc3t** [comment]
Thanks for creating this issue! I will do the `contracts` and `shared` repos

**Comment by rauljordan** [comment]
Great @terenc3t ! Can you open two issues for that and assign yourself?

**Comment by nisdas** [comment]
I can do the beacon chain repo
