### ISSUE TITLE
Collation: Check transaction does not exceed gas limit

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#37]
See TODO here: https://github.com/prysmaticlabs/geth-sharding/blob/972509a8c2d3934cb6711e467138ac471b43b344/sharding/collation.go#L33

**Comment by rauljordan** [comment]
This is not relevant as we have still not even discussed execution engines for the later phases. Let's close as I do not see this being a discussion for a while after Ruby release.

**Comment by prestonvanloon** [comment]
The TODO still exists. Please do not close issues without resolving the TODO.
https://github.com/prysmaticlabs/geth-sharding/blob/master/sharding/collation.go#L38

**Comment by terenc3t** [comment]
The TODO is no longer there. We can close this issue
