### ISSUE TITLE
Check that we are in the validator pool before calling getEligibleProposer

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#40]
Because there are no guarantees the deposit tx will be included in the immediate block, we need to first wait until we are in the validator pool before we call getEligibleProposer in the `collator.go` file.

**Comment by prestonvanloon** [comment]
This came up in gitter. Here's a link for additional context: https://gitter.im/prysmaticlabs/geth-sharding?at=5a946517458cbde557cf1e97

**Comment by terenc3t** [comment]
Merged #40, this can be closed
