### ISSUE TITLE
CollatorClient interface: Refactor Account()

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#42]
It's not a great developer experience to handle an error everytime we need to access the account for validation. If the account can be unlocked at the time the sharding client is created, then the unlocked account returned from `Account()` then we should refactor the interface from 
https://github.com/prysmaticlabs/geth-sharding/blob/972509a8c2d3934cb6711e467138ac471b43b344/sharding/collator.go#L17
to 

```
type CollatorClient interface {
   Account() *accounts.Account
   ...
}
```

**Comment by terenc3t** [comment]
resolved via #46
