### ISSUE TITLE
Collator header subscriber: Error handling

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#43]
Handle error and edge cases for the collator header subscriber.

https://github.com/prysmaticlabs/geth-sharding/blob/972509a8c2d3934cb6711e467138ac471b43b344/sharding/collator.go#L38

**Comment by rauljordan** [comment]
Thoughts on requirements for getting this closed? Let's discuss what the problems of naive disconnection would be. Would notaries lose stake? What would occur?

**Comment by prestonvanloon** [comment]
FYI this TODO has moved to https://github.com/prysmaticlabs/geth-sharding/blob/master/sharding/collator/collator.go#L32

**Comment by rauljordan** [comment]
Bump @prestonvanloon. What do you envision are the requirements to get this closed? What could a PR for this look like?

**Comment by rauljordan** [comment]
This is no longer relevant.
