### ISSUE TITLE
create a simple prompt for user to confirm 100 eth will be withdrawn

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#48]
To improve UX, and on top of joinvalidatorset flag,  I think we should create a simple prompt to let users confirm we'll be taking eth out of their account to join validator set, it could just have user type **yes** or **no** to confirm

**Comment by nisdas** [comment]
Wouldn't `-- joinvalidatorset` imply that though ? I dont think they would use that flag if they didnt intend to deposit 100 eth

**Comment by terenc3t** [comment]
Good point, I'm gonna go ahead and close this, let me know if anyone still thinks this is necessary
