### ISSUE TITLE
Collator Client Modifications

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#61]
Hi All,

As we have separated state execution and consensus into collators and proposers, respectively, we'll need to create new PR's to split up work effectively.

I propose the following potential PR's:

- [ ] Once a collator is selected, he/she needs to fetch collations from the proposals pool and take the one with the highest payout.
- [ ] Collator needs to countersign the selected collation and request the body from the proposer
- [ ] Collator needs to add collation header to the SMC and then receive a payout from the collator's deposit

Let me know if I missed anything here.

**Comment by prestonvanloon** [comment]
Can you split this into subtasks?

**Comment by rauljordan** [comment]
Closing for now. Gonna continue any discussion in  #79
