### ISSUE TITLE
Proposal Pool Implementation Notes

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#63]
Let's use this to figure out the implementation detail of the proposal pool. Propers submits collations to the proposal pool, and Validators subscribes and fetches collations from the proposal pool  Here is the functionality splits up into multiple tasks

- [ ] API to inspect collations - list the details of all the collations currently pending/queued for inclusion in the next block
- [ ] API for overall status - list the total number of collations currently pending/queued for inclusion in the next block
- [ ] Cli flags - price limit/ price bump/account slots/global slots

Let me know if I missed anything, we can start a discussion on this through here

**Comment by terenc3t** [comment]
Created the following design doc to track open questions:
https://docs.google.com/document/d/1stdJD00efftDTeofRNhSLPXY9S5O-vyhfsBBmUJOnqk/edit?usp=sharing

**Comment by nisdas** [comment]
Closing  this as not relevant anymore with the new spec
