### ISSUE TITLE
Modify Sharding Management Contract to Align With New Phase 1

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#64]
SMC needs to make the following modifications for Proposer

- [ ] add Proposer struct and mapping (similar to the Validator's stack implementation)
- [ ] functions to deposit and withdraw
- [ ] functions to verify Proposer's signature, deduct Proposer's bid from deposit upon receiving collation header

Let me know if I miss anything

**Comment by rauljordan** [comment]
# Framework to Modify SMC

(Phase 1 New Spec SMC Changes)[https://ethresear.ch/t/sharding-phase-1-spec/1407]
We will be including the methods from the SMC phase 1 spec

**Comment by prestonvanloon** [comment]
@enriquefynn can you update this issue? The requirements that @terenc3t outlined are not accurate.

**Comment by terenc3t** [comment]
Sorry, we do need to update this issue. Those requirements were before phase 1 spec

**Comment by enriquefynn** [comment]
I'll make a PR, when I have a more or less functioning implementation from the spec @rauljordan referenced. Basically what we need is in the spec, doesn't make much sense to replicate it here

**Comment by prestonvanloon** [comment]
There are some new requirements for SMC, see https://github.com/prysmaticlabs/geth-sharding/issues/89

**Comment by rauljordan** [comment]
Closing this for now for neatness purposes. We'll continue in #89.
