### ISSUE TITLE
Rename Terms Across Repository to Match New Glossary

### ISSUE THREAD

**Issue by rauljordan** [prysmaticlabs/geth-sharding#65]
Hi Everyone,

As recently mentioned on Gitter, we'll need to revise our old terminology spread out across our projects, pull requests, issues, code, and documentation to match the new glossary. The terms we have to change are the following:

- **collators** (old glossary term is validator) are agents selected by the smart contract to reach consensus on collations that will be added to the mainchain via the contract.
- **proposers** are in charge with packaging transaction data into collations along with an ETH deposit that will then be "sold" to collators.
- **sharding manager contract** is the new name for the validator manager contract. We will be managing both collators and proposers through this contract. We store proposers here because we need a place where they can lockup the ETH deposit that comes with their collation headers and automatically transfer to collators upon addition of the collation into a shard.
- **collator pool** is the new name for the validator set.

We also need to ensure that 

- **canonical chain**: The canonical collation chain of a shard, i.e. the longest chain with available collation bodies

refers to the above. In our documentation, we use canonical chain to refer to the Ethereum main chain.

Additionally, we need to mention that we will managing proposers through the SMC (**sharding manager contract**) in addition to collators, as this is an important part of the phase 1 modifications that will go public soon.

**Comment by enriquefynn** [comment]
WIP in #67

**Comment by enriquefynn** [comment]
I also think we should rename **period** to **dynasty**

**Comment by terenc3t** [comment]
WIP for code in #66
