### ISSUE TITLE
Collator connection to Ethereum node: Use any full-duplex protocol available

### ISSUE THREAD

**Issue by Magicking** [prysmaticlabs/geth-sharding#74]
Collator client actually enforce the use of IPC whereas any full-duplex (e.g: WebSocket) should work.

**Comment by prestonvanloon** [comment]
This is a nice-to-have but not a requirement for any milestone, IMO.

**Comment by Magicking** [comment]
Pebcak problem, closing.

Valid use as of #9e90de44fb1f
`geth sharding-collator [...] ws://host:port/`
without --ipcpath.
