### ISSUE TITLE
Collator design for phase 1

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#79]
Here are the functions collator needs to implement for proposal/collator game in phase 1 Sharding. Feel free to edit/add anything I missed

- [x] Fetch for incoming block headers
- [x] Check for eligible collator from SCM
- [ ] Sort proposals by highest bid
- [ ] Commitment scheme to proposers for the looked at proposals
- [ ] Challenge response scheme to answer proposer's challenge
- [ ] Windback scheme to get longest/valid chain
- [ ] Add collation header to SMC

**Comment by terenc3t** [comment]
Details: https://docs.google.com/document/d/1WRx2T6YuUr6wKCjVrv8q2Mv1-ACvJ7BAHDysnExVg44/edit#heading=h.5z805i39z8yb

**Comment by rauljordan** [comment]
A lot of this is part of the deprecated phase 1 spec, and the SMC is the only relevant part at the moment which is being worked on in #93. Closing for now.
