### ISSUE TITLE
Proposer design for phase 1

### ISSUE THREAD

**Issue by terenc3t** [prysmaticlabs/geth-sharding#80]
Here are the functions proposer needs to implement for proposal/collator game in phase 1 Sharding. Feel free to edit/add anything I missed

- [ ] Process transactions (dummy data) into collation bodies and collation headers
- [ ] Propose collation header or collation body to collator
- [ ] Check for commitment from collator
- [ ] Challenge scheme to challenge collator who doesn't download collation body

**Comment by terenc3t** [comment]
Details: https://docs.google.com/document/d/1WRx2T6YuUr6wKCjVrv8q2Mv1-ACvJ7BAHDysnExVg44/edit#heading=h.5z805i39z8yb

**Comment by nisdas** [comment]
Closing this as it is not relevant anymore with the new spec , same reason as for #59
