### ISSUE TITLE
SMC Changes for a minimal sharding protocol

### ISSUE THREAD

**Issue by prestonvanloon** [prysmaticlabs/geth-sharding#89]
The research team has identified a few new changes in "`spec 1.1`" that they are confident will not be removed in a future specification. 

High level requirements (please check off these as PRs are merged):

- [x] Anyone can call addHeader(period_id, shard_id, chunks_root) at any time. The first header to get included for a given shard in a given period gets in, all others don’t. This function just emits a log.

- [x] For every combination of shard and period, N collators (now called “notaries”) are sampled. They try to download the collation body corresponding to any header that was submitted. They can call a function submitVote(period_id, shard_id, chunks_root). This function just emits a log.

- [x] Clients read logs. If a client sees that in some shard, for some period, a chunk has been included and >= 2N/3 notaries voted for it, it accepts it as part of the canonical chain.

Assigning to SMC expert @enriquefynn for now. 
We should consider writing smaller tasks to achieve the above requirements unless this can be completed in 1 or 2 medium sized pull requests. 

References:

- [Sharding spec 1](https://ethresear.ch/t/sharding-phase-1-spec/1407) <- Now out of date!
- [Minimal sharding procotol](https://ethresear.ch/t/a-minimal-sharding-protocol-that-may-be-worthwhile-as-a-development-target-now/1650) <- The post that prompted this issue
- https://github.com/ethereum/sharding/issues/76 <- Excellent issue description by @hwwhww

**Comment by terenc3t** [comment]
Adding new requirements after latest research thread:

- [ ] SMC initializes proposer_registry per shard which keeps track of proposer deposits
- [ ] proposer client calls get_eligible_proposer to sample per shard per period
- [ ] shard uses main chain block hashes delayed by 20 mins

Reference: 
[Expanding on proposer/notary seperation](https://ethresear.ch/t/expanding-on-proposer-notary-separation/1691)

**Comment by enriquefynn** [comment]
We shouldn't use "minutes" when talking about casual time dependencies, since we don't have a real time clock.

**Comment by rauljordan** [comment]
@terenc3t thoughts on integrating the changes from the proposer/notary separation into the minimal sharding protocol? We need something we can start implementing asap.

**Comment by terenc3t** [comment]
@rauljordan We have enough information to start making changes on the SMC. I prefer we make incremental changes and open small/medium sized PR in parallel with the progress of the research side.

Besides p2p, what we can start implementing now:
- Proposer client can sample for _getEligibleProposer()_ and call _addHeader()_
- Notary client can call _submitVote()_
- SMC emits logs for _addHeader()_ and _submitVotes()_
- Client can listen to the logs

**Comment by prestonvanloon** [comment]
Some hints from py-evm https://github.com/ethereum/py-evm/issues/539

**Comment by rauljordan** [comment]
Being worked on in https://github.com/prysmaticlabs/geth-sharding/pull/93 already

**Comment by rauljordan** [comment]
@terenc3t and @prestonvanloon can we close this?

**Comment by terenc3t** [comment]
Let's close this after #97. We are almost there
